# AUTO-GENERATED by playwright-pom-agent - DO NOT EDIT.
# Re-running generation overwrites this file. Put custom logic in a subclass.
from playwright.sync_api import Page, Locator


class ConduitPage:
    def __init__(self, page: Page) -> None:
        self.page = page
        self.email_input: Locator = self.page.get_by_role('textbox', name='Email')
        self.password_input: Locator = self.page.get_by_role('textbox', name='Password')
        self.sign_in_button: Locator = self.page.get_by_role('button', name='Sign in')
