import ast

from playwright_pom_agent.generator import derive_class_name, render_pom
from playwright_pom_agent.locator_spec import LocatorSpec
from playwright_pom_agent.models import FormGroup, FormGroupField, VerificationResult, VerifiedElement


def _verified(name, spec, status=VerificationResult.UNIQUE, attempts=1):
    return VerifiedElement(name=name, locator=spec, tier=spec.tier, status=status, attempts=attempts)


def test_derive_class_name_from_title():
    assert derive_class_name("Login", "https://x.test/login") == "LoginPage"
    assert derive_class_name("", "https://x.test/checkout") == "CheckoutPage"


def test_generated_code_has_auto_generated_header():
    code = render_pom("ExamplePage", [], [])
    assert code.startswith("# AUTO-GENERATED by playwright-pom-agent - DO NOT EDIT.")
    assert "Put custom logic in a subclass." in code


def test_generated_code_is_valid_python():
    elements = [
        _verified("email_input", LocatorSpec(strategy="test_id", value="email-input")),
        _verified("submit_form", LocatorSpec(strategy="test_id", value="submit-form")),
    ]
    code = render_pom("LoginPage", elements, [])
    ast.parse(code)  # raises SyntaxError if malformed
    assert "self.email_input: Locator = self.page.get_by_test_id('email-input')" in code


def test_unverified_element_gets_comment_annotation():
    elements = [_verified("dupe", LocatorSpec(strategy="text", value="Log in"), status=VerificationResult.AMBIGUOUS, attempts=3)]
    code = render_pom("LoginPage", elements, [])
    assert "# UNVERIFIED: ambiguous match (count > 1) after 3 attempt(s)" in code


def test_form_group_generates_login_helper_regardless_of_element_naming():
    # inspector's raw hints use hyphens ("email-input"); the LLM is free to
    # name the resolved element differently as long as it normalizes the same.
    elements = [
        _verified("email_input", LocatorSpec(strategy="test_id", value="email-input")),
        _verified("password", LocatorSpec(strategy="label", value="Password")),
        _verified("remember", LocatorSpec(strategy="role", value="checkbox", role_name="Remember me")),
        _verified("submit_form", LocatorSpec(strategy="test_id", value="submit-form")),
    ]
    group = FormGroup(
        name="login",
        fields=[
            FormGroupField(element_name="email-input", input_kind="email"),
            FormGroupField(element_name="password", input_kind="text"),
            FormGroupField(element_name="remember", input_kind="checkbox"),
        ],
        submit_element_name="submit-form",
        is_login=True,
    )
    code = render_pom("LoginPage", elements, [group])
    ast.parse(code)
    assert "def login(self, email_input: str, password: str, remember: bool) -> None:" in code
    assert "self.remember.set_checked(remember)" in code
    assert "self.submit_form.click()" in code
